version: '3'

services:
  haproxy:
    hostname: haproxy
    image: haproxy:2.6-alpine
    ports:
      - '${HAPROXY_PORT}:${HAPROXY_PORT}'
      - '${HAPROXY_STATS_PORT}:${HAPROXY_STATS_PORT}' # Port For HAProxy Web UI = 18001
    networks:
      bridge-network:
        ipv4_address: '${HAPROXY_IP}'
    environment:
      - 'HAPROXY_PORT=${HAPROXY_PORT}'
      - 'HAPROXY_STATS_PORT=${HAPROXY_STATS_PORT}'
      - 'CONSUL_HOST=${CONSUL_HOST}'
    restart: unless-stopped
    volumes:
      - './haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg'

networks:
  bridge-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${NETWORK_SUBNET}'
